service: kamal-test-project

image: drajver5siti/kamal-test-project

servers:
  web:
    - 192.168.100.99

proxy:
  ssl: false
  host: kamal-test-project.local

registry:
  username: drajver5siti
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: ivan
