service: kamal-test-project

image: drajver5siti/kamal-test-project

servers:
  web:
    - 37.156.44.9

proxy:
  ssl: false
  host: kamal.peopleweek.net

registry:
  username: drajver5siti
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys: [ "./deploy.key" ]
